name: build and push
on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-build-push.yaml"

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build and push"
        required: true
        default: "latest"
        type: string
      username:
        description: "Docker Hub username"
        required: true
        default: "username"
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          build-args: |
            --build-arg BUILD_DATE=${{ github.event.head_commit.timestamp }}
            --build-arg VCS_REF=${{ github.sha }}
            --build-arg URL_ORG=${{ github.repository_owner }}
            --build-arg TOKEN_RUNNER=${{ secrets.TOKEN_RUNNER }}
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.event.inputs.tag != 'username'
        with:
          username: ${{ github.event.inputs.username }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker Hub
        uses: docker/build-push-action@v4
        if: github.event.inputs.tag != 'username'
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ github.event.inputs.username }}/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}
